name: "Build and Test"
on:
  workflow_dispatch:

  pull_request:
    branches-ignore:
      - dependabot/*

  push:
    tags-ignore:
      - "v1"

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 👷 Checkout repo
        uses: actions/checkout@v3

      - name: 🏗️ Install dependencies/prepare action
        run: npm install && npm run prepare

      - name: ✔️ Test Action
        uses: ./
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: "Starting Notification Tests"
          color: "info"

      - name: 💬 Send Test Simple Notification
        uses: ./
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: false
          title: "Notification Test"
          message: "This is an example of a simple notification with a title and a body"

      - name: 📤 Send Test Info Notification
        uses: ./
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: "Deployment Started"
          color: "info"

      - name: ⚠️ Send Test Cancelled Notification
        uses: ./
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: "Deployment Cancelled"
          color: "warning"

      - name: ⛔ Send Test Failure Notification
        uses: ./
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: "Deployment Failed"
          color: "failure"

      - name: 🎉 Send Test Success Notification
        uses: ./
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: "Deployment Successful"
          color: "success"

      - name: ✔️ Test Action Complete
        uses: ./
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: "Notification Tests Complete"
          color: "info"
