name: "test-action"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 👷 Checkout repo
        uses: actions/checkout@v2
      
      - name: ✔️ Test Action
        uses: ./
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: 'Tests Passed'
          color: '007300'

