name: "test-action"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 👷 Checkout repo
        uses: actions/checkout@v2
      
      - name: 🏗️ Install dependencies/prepare action
        run: npm install && npm run prepare
      
      - name: 🚀 Test Action
        uses: ./
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          title: 'Test Notification'
          message: 'just doing some testing over here'
