name: "test-action"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"
  workflow_dispatch:

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 👷 Checkout repo
        uses: actions/checkout@v2

      - name: ✔️ Test Action
        uses: ./
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: "Tests Passed"
          color: "success"

      - name: 📤 Send Test Info Notification
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: "Deployment Started"
          color: "info"

      - name: ⚠️ Send Test Cancelled Notification
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: "Deployment Cancelled"
          color: "warning"

      - name: ⛔ Send Test Failure Notification
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: "Deployment Failed"
          color: "failure"

      - name: 🎉 Send Test Success Notification
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: "Deployment Successful"
          color: "success"
